apiVersion: v1
kind: Service
metadata:
  name: hello-java-app-service
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: hello-app-java
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080