version: '3'
services:
  app1:
    image: department-svc
    container_name: "dep-app"
    ports:
      - "8080:8080"
    networks:
      user-department-svc-network:
        ipv4_address: 172.18.0.2
  app2:
    image: user-svc
    container_name: "usr-app"
    ports:
      - "8081:8081"
    networks:
      user-department-svc-network:
        ipv4_address: 172.18.0.3
networks:
  user-department-svc-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24